### PR TITLE
rescheduling fix

### LINKED ISSUE #41: Manual commands are not rescheduled
Running a dashboard command which takes over a subsystem cancels the manual command. At the end of its completion, the manual command is not rescheduled but it should be.

### PR DESCRIPTION
**Pull request by vladaviedov**
Closes #41

### CODE REVIEW

File: src/main/java/org/recordrobotics/munchkin/RobotContainer.java [hunk 1]
```diff
@@ -62,12 +60,12 @@ public RobotContainer() {
...
-			new ManualClimbers(_climbers, _controlInput),
-			new ManualFlywheel(_flywheel, _controlInput),
-			new ManualRotator(_rotator, _controlInput),
-			new ManualDrive(_drive, _controlInput));
+		_teleopPairs = new ArrayList<>();
+		_teleopPairs.add(new Pair<Subsystem, Command>(_acquisition, new ManualAcquisition(_acquisition, _controlInput)));
+		_teleopPairs.add(new Pair<Subsystem, Command>(_climbers, new ManualClimbers(_climbers, _controlInput)));
+		_teleopPairs.add(new Pair<Subsystem, Command>(_flywheel, new ManualFlywheel(_flywheel, _controlInput)));
+		_teleopPairs.add(new Pair<Subsystem, Command>(_rotator, new ManualRotator(_rotator, _controlInput)));
+		_teleopPairs.add(new Pair<Subsystem, Command>(_drive, new ManualDrive(_drive, _controlInput)));
```
Comment (fielia) [inline src/main/java/org/recordrobotics/munchkin/RobotContainer.java:68]: if im not mistaken, arraylists can be declared and initialized with {{}} around the .add() statements

**Review by fielia — APPROVED** [review]

File: src/main/java/org/recordrobotics/munchkin/RobotContainer.java (hunk 1 above)
Comment (vladaviedov) [reply src/main/java/org/recordrobotics/munchkin/RobotContainer.java:68]: Uhh, PMD seems to hate it
https://pmd.github.io/pmd-6.45.0/pmd_rules_java_bestpractices.html#doublebraceinitialization
